// Generated by wxt
// Types for the #import virtual module
declare module '#imports' {
  export { browser, Browser } from 'wxt/browser';
  export { storage, StorageArea, WxtStorage, WxtStorageItem, StorageItemKey, StorageAreaChanges, MigrationError } from 'wxt/utils/storage';
  export { useAppConfig } from 'wxt/utils/app-config';
  export { ContentScriptContext, WxtWindowEventMap } from 'wxt/utils/content-script-context';
  export { createIframeUi, IframeContentScriptUi, IframeContentScriptUiOptions } from 'wxt/utils/content-script-ui/iframe';
  export { createIntegratedUi, IntegratedContentScriptUi, IntegratedContentScriptUiOptions } from 'wxt/utils/content-script-ui/integrated';
  export { createShadowRootUi, ShadowRootContentScriptUi, ShadowRootContentScriptUiOptions } from 'wxt/utils/content-script-ui/shadow-root';
  export { ContentScriptUi, ContentScriptUiOptions, ContentScriptOverlayAlignment, ContentScriptAppendMode, ContentScriptInlinePositioningOptions, ContentScriptOverlayPositioningOptions, ContentScriptModalPositioningOptions, ContentScriptPositioningOptions, ContentScriptAnchoredOptions, AutoMountOptions, StopAutoMount, AutoMount } from 'wxt/utils/content-script-ui/types';
  export { defineAppConfig, WxtAppConfig } from 'wxt/utils/define-app-config';
  export { defineBackground } from 'wxt/utils/define-background';
  export { defineContentScript } from 'wxt/utils/define-content-script';
  export { defineUnlistedScript } from 'wxt/utils/define-unlisted-script';
  export { defineWxtPlugin } from 'wxt/utils/define-wxt-plugin';
  export { injectScript, ScriptPublicPath, InjectScriptOptions } from 'wxt/utils/inject-script';
  export { InvalidMatchPattern, MatchPattern } from 'wxt/utils/match-patterns';
  export { onMount, beforeUpdate, afterUpdate, onDestroy, tick, setContext, getContext, hasContext, getAllContexts, createEventDispatcher } from 'svelte';
  export { fakeBrowser } from 'wxt/testing';
  export { getAverageValue, getWuUnit, getAdpeUnit, computeResources, getGesScoreValue, calculResourcesFromAllServer, calculNetworkGes } from '../src/utils/calculator';
  export { getTabId, getTabUrl, getUrl, sendChromeMsg, sendMessageAndWait, cleanCache, reloadCurrentTab } from '../src/utils/chrome.utils';
  export { formatDate, formatDisplayZone, formatNumber, formatSize, formatScoreForGrade, formatGesMeasuresForTable, formatUriOnly, formatSimulationLabel, formatSizeTransferred, formatSizeTransferredWithUnit, formatNbRequest, formatIntensity, formatEmission, formatGes, toHistoFormattedDatas } from '../src/utils/format';
  export { filterMeasure, isNetworkResource, isCacheCall, isAfter, isRealUrl, getRealCall, getLocalStorageObject, setLocalStorageObject, getSurHead, createEmptyMeasure, scrollPrompt } from '../src/utils/utils';
  export { translate, translateHtmlUrl } from '../src/utils/lang';
  export { logErr, logWarn, logInfo, logDebug } from '../src/utils/log';
}
