// Generated by wxt
export {}
declare global {
  const ContentScriptContext: typeof import('wxt/utils/content-script-context').ContentScriptContext
  const InvalidMatchPattern: typeof import('wxt/utils/match-patterns').InvalidMatchPattern
  const MatchPattern: typeof import('wxt/utils/match-patterns').MatchPattern
  const afterUpdate: typeof import('svelte').afterUpdate
  const beforeUpdate: typeof import('svelte').beforeUpdate
  const browser: typeof import('wxt/browser').browser
  const calculNetworkGes: typeof import('C:/Users/Abdel/Desktop/conserto/GreenTrackR/src/utils/calculator').calculNetworkGes
  const calculResourcesFromAllServer: typeof import('C:/Users/Abdel/Desktop/conserto/GreenTrackR/src/utils/calculator').calculResourcesFromAllServer
  const cleanCache: typeof import('C:/Users/Abdel/Desktop/conserto/GreenTrackR/src/utils/chrome.utils').cleanCache
  const computeResources: typeof import('C:/Users/Abdel/Desktop/conserto/GreenTrackR/src/utils/calculator').computeResources
  const createEmptyMeasure: typeof import('C:/Users/Abdel/Desktop/conserto/GreenTrackR/src/utils/utils').createEmptyMeasure
  const createEventDispatcher: typeof import('svelte').createEventDispatcher
  const createIframeUi: typeof import('wxt/utils/content-script-ui/iframe').createIframeUi
  const createIntegratedUi: typeof import('wxt/utils/content-script-ui/integrated').createIntegratedUi
  const createShadowRootUi: typeof import('wxt/utils/content-script-ui/shadow-root').createShadowRootUi
  const defineAppConfig: typeof import('wxt/utils/define-app-config').defineAppConfig
  const defineBackground: typeof import('wxt/utils/define-background').defineBackground
  const defineContentScript: typeof import('wxt/utils/define-content-script').defineContentScript
  const defineUnlistedScript: typeof import('wxt/utils/define-unlisted-script').defineUnlistedScript
  const defineWxtPlugin: typeof import('wxt/utils/define-wxt-plugin').defineWxtPlugin
  const fakeBrowser: typeof import('wxt/testing').fakeBrowser
  const filterMeasure: typeof import('C:/Users/Abdel/Desktop/conserto/GreenTrackR/src/utils/utils').filterMeasure
  const formatDate: typeof import('C:/Users/Abdel/Desktop/conserto/GreenTrackR/src/utils/format').formatDate
  const formatDisplayZone: typeof import('C:/Users/Abdel/Desktop/conserto/GreenTrackR/src/utils/format').formatDisplayZone
  const formatEmission: typeof import('C:/Users/Abdel/Desktop/conserto/GreenTrackR/src/utils/format').formatEmission
  const formatGes: typeof import('C:/Users/Abdel/Desktop/conserto/GreenTrackR/src/utils/format').formatGes
  const formatGesMeasuresForTable: typeof import('C:/Users/Abdel/Desktop/conserto/GreenTrackR/src/utils/format').formatGesMeasuresForTable
  const formatIntensity: typeof import('C:/Users/Abdel/Desktop/conserto/GreenTrackR/src/utils/format').formatIntensity
  const formatNbRequest: typeof import('C:/Users/Abdel/Desktop/conserto/GreenTrackR/src/utils/format').formatNbRequest
  const formatNumber: typeof import('C:/Users/Abdel/Desktop/conserto/GreenTrackR/src/utils/format').formatNumber
  const formatScoreForGrade: typeof import('C:/Users/Abdel/Desktop/conserto/GreenTrackR/src/utils/format').formatScoreForGrade
  const formatSimulationLabel: typeof import('C:/Users/Abdel/Desktop/conserto/GreenTrackR/src/utils/format').formatSimulationLabel
  const formatSize: typeof import('C:/Users/Abdel/Desktop/conserto/GreenTrackR/src/utils/format').formatSize
  const formatSizeTransferred: typeof import('C:/Users/Abdel/Desktop/conserto/GreenTrackR/src/utils/format').formatSizeTransferred
  const formatSizeTransferredWithUnit: typeof import('C:/Users/Abdel/Desktop/conserto/GreenTrackR/src/utils/format').formatSizeTransferredWithUnit
  const formatUriOnly: typeof import('C:/Users/Abdel/Desktop/conserto/GreenTrackR/src/utils/format').formatUriOnly
  const getAdpeUnit: typeof import('C:/Users/Abdel/Desktop/conserto/GreenTrackR/src/utils/calculator').getAdpeUnit
  const getAllContexts: typeof import('svelte').getAllContexts
  const getAverageValue: typeof import('C:/Users/Abdel/Desktop/conserto/GreenTrackR/src/utils/calculator').getAverageValue
  const getContext: typeof import('svelte').getContext
  const getGesScoreValue: typeof import('C:/Users/Abdel/Desktop/conserto/GreenTrackR/src/utils/calculator').getGesScoreValue
  const getLocalStorageObject: typeof import('C:/Users/Abdel/Desktop/conserto/GreenTrackR/src/utils/utils').getLocalStorageObject
  const getRealCall: typeof import('C:/Users/Abdel/Desktop/conserto/GreenTrackR/src/utils/utils').getRealCall
  const getSurHead: typeof import('C:/Users/Abdel/Desktop/conserto/GreenTrackR/src/utils/utils').getSurHead
  const getTabId: typeof import('C:/Users/Abdel/Desktop/conserto/GreenTrackR/src/utils/chrome.utils').getTabId
  const getTabUrl: typeof import('C:/Users/Abdel/Desktop/conserto/GreenTrackR/src/utils/chrome.utils').getTabUrl
  const getUrl: typeof import('C:/Users/Abdel/Desktop/conserto/GreenTrackR/src/utils/chrome.utils').getUrl
  const getWuUnit: typeof import('C:/Users/Abdel/Desktop/conserto/GreenTrackR/src/utils/calculator').getWuUnit
  const hasContext: typeof import('svelte').hasContext
  const injectScript: typeof import('wxt/utils/inject-script').injectScript
  const isAfter: typeof import('C:/Users/Abdel/Desktop/conserto/GreenTrackR/src/utils/utils').isAfter
  const isCacheCall: typeof import('C:/Users/Abdel/Desktop/conserto/GreenTrackR/src/utils/utils').isCacheCall
  const isNetworkResource: typeof import('C:/Users/Abdel/Desktop/conserto/GreenTrackR/src/utils/utils').isNetworkResource
  const isRealUrl: typeof import('C:/Users/Abdel/Desktop/conserto/GreenTrackR/src/utils/utils').isRealUrl
  const logDebug: typeof import('C:/Users/Abdel/Desktop/conserto/GreenTrackR/src/utils/log').logDebug
  const logErr: typeof import('C:/Users/Abdel/Desktop/conserto/GreenTrackR/src/utils/log').logErr
  const logInfo: typeof import('C:/Users/Abdel/Desktop/conserto/GreenTrackR/src/utils/log').logInfo
  const logWarn: typeof import('C:/Users/Abdel/Desktop/conserto/GreenTrackR/src/utils/log').logWarn
  const onDestroy: typeof import('svelte').onDestroy
  const onMount: typeof import('svelte').onMount
  const reloadCurrentTab: typeof import('C:/Users/Abdel/Desktop/conserto/GreenTrackR/src/utils/chrome.utils').reloadCurrentTab
  const scrollPrompt: typeof import('C:/Users/Abdel/Desktop/conserto/GreenTrackR/src/utils/utils').scrollPrompt
  const sendChromeMsg: typeof import('C:/Users/Abdel/Desktop/conserto/GreenTrackR/src/utils/chrome.utils').sendChromeMsg
  const sendMessageAndWait: typeof import('C:/Users/Abdel/Desktop/conserto/GreenTrackR/src/utils/chrome.utils').sendMessageAndWait
  const setContext: typeof import('svelte').setContext
  const setLocalStorageObject: typeof import('C:/Users/Abdel/Desktop/conserto/GreenTrackR/src/utils/utils').setLocalStorageObject
  const storage: typeof import('wxt/utils/storage').storage
  const tick: typeof import('svelte').tick
  const toHistoFormattedDatas: typeof import('C:/Users/Abdel/Desktop/conserto/GreenTrackR/src/utils/format').toHistoFormattedDatas
  const translate: typeof import('C:/Users/Abdel/Desktop/conserto/GreenTrackR/src/utils/lang').translate
  const translateHtmlUrl: typeof import('C:/Users/Abdel/Desktop/conserto/GreenTrackR/src/utils/lang').translateHtmlUrl
  const useAppConfig: typeof import('wxt/utils/app-config').useAppConfig
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Browser } from 'wxt/browser'
  import('wxt/browser')
  // @ts-ignore
  export type { StorageArea, WxtStorage, WxtStorageItem, StorageItemKey, StorageAreaChanges, MigrationError } from 'wxt/utils/storage'
  import('wxt/utils/storage')
  // @ts-ignore
  export type { WxtWindowEventMap } from 'wxt/utils/content-script-context'
  import('wxt/utils/content-script-context')
  // @ts-ignore
  export type { IframeContentScriptUi, IframeContentScriptUiOptions } from 'wxt/utils/content-script-ui/iframe'
  import('wxt/utils/content-script-ui/iframe')
  // @ts-ignore
  export type { IntegratedContentScriptUi, IntegratedContentScriptUiOptions } from 'wxt/utils/content-script-ui/integrated'
  import('wxt/utils/content-script-ui/integrated')
  // @ts-ignore
  export type { ShadowRootContentScriptUi, ShadowRootContentScriptUiOptions } from 'wxt/utils/content-script-ui/shadow-root'
  import('wxt/utils/content-script-ui/shadow-root')
  // @ts-ignore
  export type { ContentScriptUi, ContentScriptUiOptions, ContentScriptOverlayAlignment, ContentScriptAppendMode, ContentScriptInlinePositioningOptions, ContentScriptOverlayPositioningOptions, ContentScriptModalPositioningOptions, ContentScriptPositioningOptions, ContentScriptAnchoredOptions, AutoMountOptions, StopAutoMount, AutoMount } from 'wxt/utils/content-script-ui/types'
  import('wxt/utils/content-script-ui/types')
  // @ts-ignore
  export type { WxtAppConfig } from 'wxt/utils/define-app-config'
  import('wxt/utils/define-app-config')
  // @ts-ignore
  export type { ScriptPublicPath, InjectScriptOptions } from 'wxt/utils/inject-script'
  import('wxt/utils/inject-script')
}
